### ISSUE TITLE
Map.!: given key is not an element in the map when using elm make --debug

### ISSUE THREAD

**Issue by idarous** [elm/compiler#1885] opened 2019-01-21 14:20 UTC
Hello,

I have a problem with the elm compiler.

When I compiling my project with the following command `elm make src/Main.elm`, the code compiles correctly.

But, when I compile my project with the debug flag like this `elm make src/Main.elm` I have the following message.

```
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at ./Data/Map/Internal.hs:610:17 in containers-0.5.11.0-K2TDqgYtGUcKxAY1UqVZ3R:Data.Map.Internal
```

I don't think that's a normal behaviour.
Can someone explain me why I have this problem?

**Comment by jesse-c** [comment] 2019-01-22 15:25
I believe this is a dupe of https://github.com/elm/compiler/issues/1851.

**Comment by domenkozar** [comment] 2019-02-10 07:12
you could check if https://github.com/elm/compiler/pull/1850 fixes it for you

**Comment by evancz** [comment] 2019-07-10 16:56
I cannot reproduce without an http://sscce.org/

That said, I believe this is the same as other reports about `--debug` and `Map.!` which should be resolved in the development version of the compiler. So the fix should be out with the next Elm release.

**Closed by evancz** 2019-07-10 16:56 UTC
Labels: no sscce
