### ISSUE TITLE
Move the project to stack

### ISSUE THREAD

**Issue by radrow** [elm/compiler#2157] opened 2020-12-14 18:16 UTC
Stack projects are much easier to manage and work with. Why not consider moving from raw cabal to it? It would make contributing and general development much nicer. Also, the switch is not a big deal anyway. 

Purescript uses stack, just sayin'

**Comment by Razzeee** [comment] 2020-12-14 23:31
Duplicate of https://github.com/elm/compiler/pull/1980 unless the view changed

**Comment by evancz** [comment] 2021-02-03 19:28
I like to use `cabal` for development. I have had problems with `stack` in the past.

**Closed by evancz** 2021-02-03 19:28 UTC
