### ISSUE TITLE
Directory links in reactor are broken

### ISSUE THREAD

**Issue by nikita-volkov** [elm/compiler#1943] opened 2019-06-21 18:21 UTC
**Quick Summary:** Clicking on directory leads to nowhere because they begin with double slash.

![image](https://user-images.githubusercontent.com/1560937/59943068-08682d00-946a-11e9-8d8a-18f879d5c319.png)

![image](https://user-images.githubusercontent.com/1560937/59943135-259cfb80-946a-11e9-966e-a6ce5778fb0e.png)

## SSCCE

- **Elm:** 0.19.0
- **Browser:** Chrome 74.0.3729.169
- **Operating System:** Mac OS 10.14.1

**Comment by jhrcek** [comment] 2019-06-23 04:56
This is duplicate of https://github.com/elm/compiler/issues/1758 which has more details about the root cause

**Closed** 2019-06-23 11:10 UTC
