### ISSUE TITLE
`elm reactor` gives a vague error on circular dependencies

### ISSUE THREAD

**Issue by trenneman** [elm/compiler#1742] opened 2018-07-31 07:18 UTC
See #1741. I've tried running the SSCCE on multiple machines and OSes and the issue is present in all cases. I am running **Elm 0.19 Alpha**. Could that make the difference?

Ran the following with Elm 0.19 on:
* Arch Linux using Chrome Version 67.0.3396.99 (Official Build) (64-bit);
* Arch Linux using Chrome Version 68.0.3440.75 (Official Build) (64-bit);
* Arch Linux using Firefox 61.0 (64-bit);
* Windows 10 using Chrome Version 66.0.3359.181 (Official Build) (64-bit);
* Windows 10 using Chrome Version 68.0.3440.75 (Official Build) (64-bit);

Also in Incognito mode the issue is present.

```
$ git clone --single-branch -b elm-reactor-circular-dependencies git@github.com:trenneman/sscce.git
$ /path/to/elm make src/Main.elm
Dependencies loaded from local cache.
Dependencies ready!                
-- IMPORT CYCLE ----------------------------------------------------------------

Your module imports form a cycle:

    ┌─────┐
    │    Bar
    │     ↓
    │    Foo
    └─────┘

Learn more about why this is disallowed and how to break cycles
here:<https://elm-lang.org/0.19.0/import-cycles>

$ ./elm reactor
```

While `elm make` gives the correct error, loading the page at http://localhost:8000/src/Main.elm returns: `Problem with the value at json.path: null Expecting a STRING`:

![elm-reactor-circular-dependency](https://user-images.githubusercontent.com/2738701/43443522-6556c680-94a1-11e8-8dec-df3773ac92af.png)

**Comment by evancz** [comment] 2018-08-02 17:12
Interesting! I guess I have it fixed locally then. I am always running the latest build, so I guess one of the [recent commits](https://github.com/elm/compiler/commits/master) must have fixed it. There have been some since the last round of binaries, so maybe something like https://github.com/elm/compiler/commit/b5dcc460f1de27915e416b56f92f11de70588b0a did it.

To be double sure, I downloaded the latest public round of binaries and could reproduce. So the SSCCE works on macs as well, just not ones that have the dev build :)

Anyway, I think the best course of action is to check with the next round of binaries. Sorry for the somewhat chaotic issue opening and closing around this, and thank you for reporting it!

**Closed by evancz** 2018-08-02 17:12 UTC

**Comment by trenneman** [comment] 2018-08-03 08:38
Even better if you fixed it already! I'll give it another try in the next round. Thanks.

**Comment by trenneman** [comment] 2018-08-26 11:07
Works like a charm with the official 0.19!
