### ISSUE TITLE
Compiler (0.19.0) does not notice if module hides previously exported variable

### ISSUE THREAD

**Issue by nonpop** [elm/compiler#1779] opened 2018-09-02 08:58 UTC
- Start with a project with the following files:
- elm.json (nothing special, just a package exposing ModuleA)
```elm
{
    "type": "package",
    "name": "sscce/sscce",
    "summary": "sscce",
    "license": "BSD-3-Clause",
    "version": "1.0.0",
    "exposed-modules": ["ModuleA"],
    "elm-version": "0.19.0 <= v < 0.20.0",
    "dependencies": {
        "elm/core": "1.0.0 <= v < 2.0.0"
    },
    "test-dependencies": {}
}
```
- src/ModuleA.elm
```elm
module ModuleA exposing (a)

import ModuleB

a = ModuleB.b
```
- src/ModuleB.elm
```elm
module ModuleB exposing (b, dummy)

b = ()
dummy = ()
```

- Compile with `elm make`. It should succeed.
- Next, remove `b` from the exposing list of `ModuleB`.
- Compile again, and it succeeds (!).
- Remove `elm-stuff` and now compilation fails as expected, complaining that `ModuleB` does not expose `b`.

**Comment by evancz** [comment] 2019-07-30 22:37
I am not able to reproduce this with Elm 0.19.0 on my computer.

There are some improvements in the development branch of the compiler to catch cases _like_ this though. https://github.com/elm/compiler/issues/1956 has an SSCCE that was broken with 0.19.0 and fixed with the development build.

If you can reproduce your case with 0.19.0, let me know. I am seeing that it works with 0.19.0 and the development branch (which should be better with this kind of case anyway!) so we should close if it cannot be reproduced.

**Comment by evancz** [comment] 2019-07-30 22:45
I was able to reproduce the error with a slight modification to the instructions. Once you have the files set up, you need to do:

```
$ elm make 
Success! Compiled 2 modules.

# tweak src/ModuleB.elm

$ elm make src/ModuleB.elm 
Success! Compiled 1 module.                                          
$ elm make 
Success!
```

You may have an editor plugin that runs `elm make PATH` on save which made it unnecessary to run that command by hand.

* * *

Anyway, a similar bug was reported in https://github.com/elm/compiler/issues/1956 and fixed in the development build of the compiler. Using the dev build, I am now seeing the following if I try with your SSCCE:

```
$ ./elm make 
Success! Compiled 2 modules.

# tweak src/ModuleB.elm

$ ./elm make src/ModuleB.elm 
Success! Compiled 1 module.
$ ./elm make 
Detected problems in 1 module.
-- NAMING ERROR ------------------------------------------------ src/ModuleA.elm

I cannot find a `ModuleB.b` variable:

5| a = ModuleB.b
       ^^^^^^^^^
The `ModuleB` module does not expose a `b` variable. These names seem close
though:

    ModuleB.dummy
    modBy
    round
    toFloat

Hint: Read <https://elm-lang.org/0.19.1/imports> to see how `import`
declarations work in Elm.
```

So it looks like it is fixed in the development version! Thank you for reporting this, and the fix should be available along with a bunch of other improvements once 0.19.1 is released.

**Closed by evancz** 2019-07-30 22:45 UTC
