### ISSUE TITLE
npm incorrect latest version in some circumstances

### ISSUE THREAD

**Issue by frederikhors** [elm/compiler#1928] opened 2019-04-24 20:28 UTC
I'm installing elm for the first time with `npm i -g elm`.

It installs the `0.19.0-bugfix6` version but if I check the latest one with `npm-check -guE` (https://www.npmjs.com/package/npm-check) it finds a new version: `2.0.0`.

I think because of these versions on npmjs.com: https://www.npmjs.com/package/elm?activeTab=versions

Can we fix it removing those versions?

**Comment by frederikhors** [comment] 2019-04-24 20:32
https://github.com/dylang/npm-check/issues/314

**Comment by evancz** [comment] 2019-05-06 20:58
I don't think it's possible to remove those versions.

All the NPM installer does is download the binaries from https://github.com/elm/compiler/releases/tag/0.19.0, and the problem is that initially the versioning of the `npm` installer did not match the actual Elm project. So that version comes from four years ago before we knew it'd be confusing if the versions didn't match.

That version is marked as deprecated though, so it may be that `npm-check` is not taking deprecation notices into account.

Anyway, we have some plans to try to clean up whatever is going on in NPM world that's leading to weird messages about the Elm installer. Sorry for the trouble in the meantime.

**Closed by evancz** 2019-05-06 20:58 UTC
