### ISSUE TITLE
Map.!: given key is not an element in the map

### ISSUE THREAD

**Issue by simonh1000** [elm/compiler#1817] opened 2018-10-01 20:04 UTC
Compiler error SSCCE - toggle commenting App/Login/Update line 35 `Animate Animation.Msg`

Based on the code provided at https://github.com/elm/compiler/issues/1796 but stripped down 

[Archive.zip](https://github.com/elm/compiler/files/2435426/Archive.zip)

**Comment by pdamoc** [comment] 2018-10-02 06:45
The error only happens (for me) when compilation is done with `--debug`.

Also, the minimal example to reproduce this is: 

```elm
module Main exposing (main)

import Animation
import Browser
import Html


type Msg
    = LoginMsg Animation.Msg


main : Program () Int Msg
main =
    Browser.element
        { init = \_ -> ( 0, Cmd.none )
        , subscriptions = \_ -> Sub.none
        , update = \_ m -> ( m, Cmd.none )
        , view = \_ -> Html.text ""
        }
```
with `mdgriffith/elm-style-animation` installed.

**Comment by pdamoc** [comment] 2018-10-02 06:54
If I copy the `elm-style-animation` source code into the `src` folder of the SSCCE and add the `elm/time` and `elm/svg` dependencies (from `elm-style-animation`), the error goes away.

**Comment by dtraft** [comment] 2018-10-02 12:32
Experiencing the exact same issue as @pdamoc and @simonh1000 with the elm-form package (https://package.elm-lang.org/packages/etaque/elm-form/latest), and can confirm that moving the source code into the `src` folder resolves the problem.

**Comment by simonh1000** [comment] 2018-10-02 14:20
Just for the record, I'm not using either of these and get the error (presumably from some other - sufficiently complex - import)

**Comment by nullbio** [comment] 2018-10-03 04:52
Also getting this error, but uncertain where it's coming from.

My imports include:

```{
    "type": "application",
    "source-directories": [
        "src",
        "src/Page"
    ],
    "elm-version": "0.19.0",
    "dependencies": {
        "direct": {
            "elm/browser": "1.0.0",
            "elm/core": "1.0.0",
            "elm/html": "1.0.0",
            "elm/http": "1.0.0",
            "elm/json": "1.0.0",
            "elm/time": "1.0.0",
            "elm/url": "1.0.0",
            "tiziano88/elm-protobuf": "3.0.0"
        },
        "indirect": {
            "elm/regex": "1.0.0",
            "elm/virtual-dom": "1.0.0",
            "jweir/elm-iso8601": "5.0.2"
        }
    },
    "test-dependencies": {
        "direct": {},
        "indirect": {}
    }
}
```

```
> elm make src/Main.elm 
Success! Compiled 10 modules.                                        
elm: Map.!: given key is not an element in the map
CallStack (from HasCallStack):
  error, called at ./Data/Map/Internal.hs:610:17 in containers-0.5.11.0-K2TDqgYtGUcKxAY1UqVZ3R:Data.Map.Internal
```

I get this error without the `--debug` flag and without the animation import.

**Comment by synalysis** [comment] 2018-10-04 19:54
Another sample code attached. (using slashmili/phoenix-socket)
The problem occurs only in debug build.
It disappears when I remove in Main.elm `Channel.Msg` from
   `ChannelMessage Channel.Msg`
or `(PhxMsg.Msg Msg)` in Channel.elm
[compiler-error.zip](https://github.com/elm/compiler/files/2447939/compiler-error.zip)

**Comment by rtfeldman** [comment] 2018-10-04 23:46
Thanks for the SSCCEs, all!

What is the smallest example anyone's seen of reproducing this **without** `--debug`?

(So far it seems to be reproducible in smaller examples with `--debug`, but all the examples that reproduce it without `--debug` are a lot bigger. Maybe I'm missing one though!)

**Comment by nullbio** [comment] 2018-10-05 01:43
@rtfeldman From what I've seen from the bug reports the cases without `--debug` (mine included) are fixed by clearing the `elm-stuff` folder. Not sure if there are exceptions to that, but if there aren't then wouldn't this indicate a problem with a stale or missing package, and as such would make it difficult to reproduce consistently?

**Comment by rtfeldman** [comment] 2018-10-05 01:48
Definitely, but unfortunately bugs that are difficult to reproduce consistently are also difficult to fix. 😅

**Comment by rtfeldman** [comment] 2018-10-05 02:10
Incidentally the reason I'm asking is that the `--debug` one and the one without `--debug` seem to be unrelated.

(Evan tracked down the cause of the `--debug` one, and is currently evaluating different fixes based on their compile time performance characteristics.)

So if anyone can find a SSCCE that is consistently reproducible (presumably with "build it, then change this, then build again" since the bug seems to be related to caching given that deleting `elm-stuff` fixes it), that would be super helpful!

**Comment by synalysis** [comment] 2018-10-05 06:59
> So if anyone can find a SSCCE that is consistently reproducible (presumably with "build it, then change this, then build again" since the bug seems to be related to caching given that deleting `elm-stuff` fixes it), that would be super helpful!

The case I uploaded above happens only in debug mode but doesn't go away by deleting `elm-stuff`. There are two places in the code where I can make the problem go away. Happened on macOS 10.13.6 with Elm 0.19.0 installed with ASDF.

**Comment by rtfeldman** [comment] 2018-10-05 09:45
@synalysis sorry, edited to clarify that I meant a SSCCE for the bug without `--debug`. All set on the `--debug` one already!

**Comment by synalysis** [comment] 2018-10-05 18:06
> @synalysis sorry, edited to clarify that I meant a SSCCE for the bug without `--debug`. All set on the `--debug` one already!

Great! :-) Just wanted to provide a reproducible case that doesn't require deletion of `elm-stuff`.
What is the procedure to get such a fix? I see no change in the public repository so far. Will this only be available with a 0.19.1 version? I don't want to put pressure on someone, it's just about deciding how to proceed with my development.

**Comment by rtfeldman** [comment] 2018-10-05 18:17
We've talked about a potential 0.19.1 (with complete backwards compatibility with 0.19.0), but no firm plans yet!

**Comment by hayesgm** [comment] 2018-10-16 13:41
Do you have information on what causes the bug so we can at least avoid the issue until a fix is made?

**Comment by synalysis** [comment] 2018-10-16 14:49
> Do you have information on what causes the bug so we can at least avoid the issue until a fix is made?

@hayesgm for me it was sufficient to download the sources of the lib I used and reference them directly in elm.json like this:

```
    "source-directories": [
        "src",
        "extern/phoenix-socket-4.2.1/src"
    ],

```

**Comment by joachimdb** [comment] 2018-10-16 17:40
@hayesgm We had the same problem, fixed it by moving the bad dependency (torreyatcitty/the-best-decimal in our case) to "indirect" in out elm.json

**Comment by hayesgm** [comment] 2018-10-16 23:18
@JasonJAyalaP Yup, for me, I did (in a project with my code in `src/elm`):

```
cd src/elm
git clone https://github.com/torreyatcitty/the-best-decimal.git
rm -r the-best-decimal/.git
```

Then I went into my elm.json, removed `torreyatcitty/the-best-decimal`, promoted `"cmditch/elm-bigint": "1.0.1"` to direct and added `"src/the-best-decimal/src"` to source-directories.

Happy to make the changes to fix `the-best-decimal` if we knew what the issue was.

**Comment by Munksgaard** [comment] 2018-10-31 13:50
I have the same problem, but in my case it was caused by the krisajenkins/remotedata package. Adding it directly to source-directories worked, but it's not really a long term solution.

**Comment by krksgbr** [comment] 2018-11-13 13:22
@aaronwhite i'd be interested in trying your Dockerfile. cheers!

**Comment by jesse-c** [comment] 2018-11-13 15:05
@aaronwhite I'm definitely interested in trying it out

**Comment by arsduo** [comment] 2018-11-17 02:33
@aaronwhite I'd also be interested in trying it out! I just ran into the problem with `--debug` enabled.

**Comment by woylie** [comment] 2018-11-20 09:00
@aaronwhite I'm also interested. I also have the problem with `--debug` enabled.

**Comment by aaronwhite** [comment] 2018-11-21 03:00
So not near my machine w/ the docker build, but looks like Evan is closing these issues to consolidate. Let me just sneak in some notes for him or others if interested:

the bug exists somewhere in `Extract.hs` (used for generating debug info), it’s beyond me to solve it, but if you instrument `extractUnion`’s map access w/ something along the lines of `case I.toUnionInternals (unions ! traceShow (N.toString name) name) of` the (new) Elm compiler will spit out problematic tag names as it goes, the last one you see is your issue (you may need to repeat this multiple times). (edited)

**Comment by dbottisti** [comment] 2018-12-30 22:51
I'd like to add another SSCCE.  Seems to be a problem when putting an `Array` within a union type.  Changing `Array` to `List` in the example below does not trigger the error.

```elm
module Main exposing (..)

import Browser
import Array exposing (Array)
import Html exposing (Html, text)

main : Program () Model Msg
main = Browser.sandbox { init = model, view = view, update = update }

type alias Model = Int

model : Model
model = 0

type Msg = PerformAction (Array String)

update : Msg -> Model -> Model
update msg m =
    case msg of
        PerformAction _ ->
            m

view : Model -> Html Msg
view m =
    text (String.fromInt m)
```

**Comment by evancz** [comment] 2019-07-19 17:47
Anything having to do with `--debug` causing problems for certain types should be fixed by changes made in the development version. Some details on the fix are available at https://github.com/elm/compiler/pull/1850#issuecomment-509327575

The next compiler release will be 0.19.1, and the fix will become available then (alongside with a bunch of other improvements!)

**Closed by evancz** 2019-07-19 17:47 UTC

**Comment by flurin-conradin** [comment] 2019-08-29 08:59
hello everyone

I am facing the same issue and I not sure how to tackle it. Just as a heads-up, sorry I cannot provide any useful information at this stage. I am on boarding to an existing application in which case it would be very useful to use the `--debug` flag. 

I understand some people were able to come up with a workaround by either changing message types or downloading dependencies. 

How would I find out what to tackle first?

Another approach would be to install the development version, I suppose. Is this described somewhere?

Many thanks in advance!

**Comment by FranzSkuffka** [comment] 2019-08-29 09:05
@flurin-conradin I would recommend getting the development version. You will need to download the binary for your system and then update the `elm.json` to use `0.19.1`. See https://discourse.elm-lang.org/t/community-beta-for-elm-0-19-1/4102.

If you are using create-elm-app I have writtin instructions here: https://discourse.elm-lang.org/t/community-beta-for-elm-0-19-1/4102/26?u=franzskuffka
