### ISSUE TITLE
Top-level `==` causes parser error in Repl

### ISSUE THREAD

**Issue by timbuckley** [elm/compiler#1787] opened 2018-09-05 19:27 UTC
I get a parser error in the REPL with just regular `==`, regardless of what data type (strings, chars, numbers), and regardless of whether I bind the variables first.

```elm
 > 'a' == 'a'
-- PARSE ERROR ------------------------------------------------------------- elm

Something went wrong while parsing your code.

3| 'a' == 'a'
   ^
I was expecting:

  - a declaration, like `x = 5` or `type alias Model = { ... }`
  - the `import` keyword
  - a doc comment, like {-| this -}
```
```elm
> "" == ""
-- PARSE ERROR ------------------------------------------------------------- elm

Something went wrong while parsing your code.

3| "" == ""
   ^
I was expecting:

  - a declaration, like `x = 5` or `type alias Model = { ... }`
  - the `import` keyword
  - a doc comment, like {-| this -}
```

There's no problem if `==` is used in inside of an expression.
```elm
> x = 2 == 2
> y = 'a' == 'b'
> x
True : Bool
> y
False : Bool
```
Another working example (using `==` to make a partial function):
```elm
> List.map ((==) 2) [1,2,3,4,5]
[False,True,False,False,False]
    : List Bool
```

**Comment by rlefevre** [comment] 2018-09-05 19:45
Note that it works with parentheses:
```
> ('a' == 'a')
True : Bool
> (0 == 0)
True : Bool
```

**Comment by pzp1997** [comment] 2018-09-05 22:43
I think this is a duplicate of #1736.

**Comment by timbuckley** [comment] 2018-09-06 02:42
@pzp1997 You are right, thanks for pointing it out. (Leaving this issue open however, since duplicate issues are okay by Evan.)

**Comment by evancz** [comment] 2018-11-20 00:04
I'll use #1736 as the canonical one for this particular problem. It is simple enough that a meta issue is not necessary!

**Closed by evancz** 2018-11-20 00:04 UTC
